theme: jekyll-theme-cayman

baseurl: "/dbt-teach-in"

plugins:
  - jekyll-relative-links
  - github-pages

relative_links:
  enabled: true
  collections: false

exclude:
  - "dbt_teach_in/dbt_modules/"
  - "dbt_teach_in/*/*/*.md"
  - "dbt_teach_in/*/*.md"
  - .idea/
  - venv/

include:
  - README.md
