dbt_teach_in:
  outputs:
    dev:
      type: postgres
      threads: 8
      host: localhost
      port: 5432
      user: postgres
      pass: docker
      dbname: postgres
      schema: dbt
  target: dev
