dbt_teach_in:
  outputs:
    dev:
      type: postgres
      threads: 8
      host: localhost
      port: 5432
      user: postgres
      pass: docker
      dbname: postgres
      schema: dbt
    redshift:
      type: redshift
      threads: 8
      host: redshift-nc.moneylion.com
      port: 5439
      user: blee
      pass: "{{ env_var('PASS') }}"
      dbname: mlsegment
      schema: usr_blee
  target: dev
